// generated by `sqlx migrate build-script`
fn main() {
    // trigger recompilation when a new migration is added
    // or a new translation file is added
    println!("cargo:rerun-if-changed=../migrations");
}
