error-contact = Believe we've made a mistake in showing you this error?
    .contact-link = Contact us!

error-core-badrequest = The browser (or proxy) sent a request that this server could not understand.
error-core-invalidheadervalue = The value for the header '{ $header }' could not be processed.
error-core-unauthorized = The server could not verify that you are authorized to access the URL requested. You either supplied the wrong credentials (e.g. a bad password) or your browser doesn't understand how to supply the credentials required.
error-core-forbidden = You don't have the permission to access the requested resource. It is either read-protected or not readable by the server.
error-core-missingpermissions = You do not have the pointercrate permissions to perform this request. Required is: { $required-permission }, which isn't contained in any of your permissions.
error-core-notfound = The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
error-core-methodnotallowed = The method is not allowed for the requested URL.
error-core-conflict = A conflict happened while processing the request. The resource might have been modified while the request was being processed.
error-core-lengthrequired = A request with this methods requires a valid 'Content-Length' header.
error-core-preconditionfailed = The precondition on the request for the URL failed positive evaluation.
error-core-payloadtoolarge = The data value transmitted exceeds the capacity limit.
error-core-unsupportedmediatype = The server does not support the media type transmitted in the request/no media type was specified. Expected one '{ $expected-type }'.
error-core-unprocessableentity = The request was well-formed but was unable to be followed due to semantic errors.
error-core-invalidpaginationlimit = Invalid value for the 'limit' parameter. It must be between 1 and 100.
error-core-invalidurlscheme = Invalid URL scheme. Only 'http' and 'https' are supported.
error-core-urlauthenticated = The provided URL contains authentication information. For security reasons it has been rejected.
error-core-invalidurlformat = The given URL does not lead to a video. The URL format for the given host has to be '{ $expected-format }'.
error-core-aftersmallerbefore = The 'after' value provided for pagination is smaller than the 'before' value. This would result in an empty response and is most likely a bug.
error-core-mutuallyexclusive = Your request contains mutually exclusive fields. Please restrict yourself to one of them.
error-core-preconditionrequired = This request is required to be conditional; try using "If-Match".
error-core-ratelimited = { $message } Try again in { $remaining-duration }.
error-core-internalservererror = The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application. Please notify a server administrator and have them look at the server logs!
error-core-databaseerror = Internally, an invalid database access has been made. Please notify a server administrator and have them look at the server logs!
error-core-querytimeout = Internally, a database query timed out. This could be due to high server load, or because of a logic error resulting in a deadlock. If this issue persists after retrying, please notify a server administrator!
error-core-databaseconnectionerror = Failed to retrieve connection to the database. The server might be temporarily overloaded.
error-core-readonlymaintenance = The website is currently in read-only maintenance mode.
