-- Add down migration script here
-- This migration is undone by the previous one, as it is impossible to restore the partially broken state 
-- introduced by only applying 20240725201300_better_raw_footage.up.sql (function with wrong return type).