-- Add down migration script here
DELETE FROM subdivisions;

INSERT INTO subdivisions (iso_code, name, nation) 
VALUES
    ('WA', 'Washington', 'US'),
    ('MD', 'Maryland', 'US'), 
    ('WV', 'West Virginia', 'US'), 
    ('NY', 'New York', 'US'), 
    ('NJ', 'New Jersey', 'US'), 
    ('PA', 'Pennsylvania', 'US'), 
    ('VA', 'Virginia', 'US'), 
    ('KY', 'Kentucky', 'US'), 
    ('OH', 'Ohio', 'US'), 
    ('IN', 'Indiana', 'US'), 
    ('IL', 'Illinois', 'US'), 
    ('MI', 'Michigan', 'US'), 
    ('WI', 'Wisconsin', 'US'), 
    ('CT', 'Connecticut', 'US'), 
    ('RI', 'Rhode Island', 'US'), 
    ('VT', 'Vermont', 'US'), 
    ('NH', 'New Hampshire', 'US'),
    ('MA', 'Massachusetts', 'US'), 
    ('ME', 'Maine', 'US'), 
    ('AL', 'Alabama', 'US'), 
    ('GA', 'Georgia', 'US'), 
    ('SC', 'South Carolina', 'US'), 
    ('FL', 'Florida', 'US'), 
    ('MS', 'Mississippi', 'US'), 
    ('TN', 'Tennessee', 'US'), 
    ('NC', 'North Carolina', 'US'), 
    ('TX', 'Texas', 'US'), 
    ('OK', 'Oklahoma', 'US'),
    ('NM', 'New Mexico', 'US'),
    ('NE', 'Nebraska', 'US'), 
    ('SD', 'South Dakota', 'US'), 
    ('KS', 'Kansas', 'US'), 
    ('CO', 'Colorado', 'US'), 
    ('ND', 'North Dakota', 'US'), 
    ('AR', 'Arkansas', 'US'), 
    ('MO', 'Missouri', 'US'), 
    ('LA', 'Louisiana', 'US'),
    ('IA', 'Iowa', 'US'), 
    ('MN', 'Minnesota', 'US'), 
    ('AZ', 'Arizona', 'US'), 
    ('NV', 'Nevada', 'US'), 
    ('CA', 'California', 'US'), 
    ('UT', 'Utah', 'US'), 
    ('OR', 'Oregon', 'US'), 
    ('MT', 'Montana', 'US'), 
    ('ID', 'Idaho', 'US'), 
    ('WY', 'Wyoming', 'US'), 
    ('HI', 'Hawaii', 'US'), 
    ('AK', 'Alaska', 'US'), 
    ('DC', 'Washington, District of Columbia', 'US'),
    ('DE', 'Delaware', 'US'),
    ('MB', 'Manitoba', 'CA'), 
    ('NT', 'Northwest Territories', 'CA'), 
    ('NL', 'Newfoundland and Labrador', 'CA'), 
    ('NU', 'Nunavut', 'CA'), 
    ('QC', 'Quebec', 'CA'),
    ('BC', 'British Columbia', 'CA'), 
    ('SK', 'Saskatchewan', 'CA'), 
    ('AB', 'Alberta', 'CA'), 
    ('ON', 'Ontario', 'CA'), 
    ('NB', 'New Brunswick', 'CA'), 
    ('NS', 'Nova Scotia', 'CA'), 
    ('PE', 'Prince Edward Island', 'CA'), 
    ('YT', 'Yukon', 'CA'), 
    ('SCT', 'Scotland', 'GB'), 
    ('WLS', 'Wales', 'GB'), 
    ('ENG', 'England', 'GB'),
    ('NIR', 'Northern Ireland', 'GB'), 
    ('ACT', 'Australian Capital Territory', 'AU'), 
    ('TAS', 'Tasmania', 'AU'),
    ('NT', 'Northern Territory', 'AU'), 
    ('WA', 'Western Australia', 'AU'), 
    ('QLD', 'Queensland', 'AU'), 
    ('NSW', 'New South Wales', 'AU'),
    ('VIC', 'Victoria', 'AU'), 
    ('SA', 'South Australia', 'AU');