error-demonlist-geolocationfailed = Geolocation failed!
error-demonlist-malformedvideourl = Malformed video URL
error-demonlist-bannedfromsubmissions = You are banned from submitting records to the demonlist!
error-demonlist-claimunverified = Your claim on this player is unverified
error-demonlist-vpsdetected = IP geolocation attempt through VPS detected
error-demonlist-nothirdpartysubmissions = This player has requested that only they themselves can submit their records
error-demonlist-submitternotfound = No submitter with id { $id } found
error-demonlist-notenotfound = No note with id { $note-id } found on record with id { $record-id }
error-demonlist-creatornotfound = Player with id { $player-id } is no creator of demon with id { demon-id }
error-demonlist-nationalitynotfound = No nationality with iso code { $iso-code } found
error-demonlist-subdivisionnotfound = No subdivision with code { $subdivision-code } found in nation { $nation-code }
error-demonlist-playernotfound = No player with id { $player-id } found
error-demonlist-playernotfoundname = No player with name { $player-name } found
error-demonlist-demonnotfound = No demon with id { $demon-id } found
error-demonlist-demonnotfoundname = No demon with name { $demon-name } found
error-demonlist-demonnotfoundposition = No demon at position { $demon-position } found
error-demonlist-listnotfound = This list does not exist
error-demonlist-recordnotfound = No record with id { $record-id } found
error-demonlist-claimnotfound = No claim by user { $member-id } on player { $player-id } found
error-demonlist-creatorexists = This player is already registered as a creator on this demon
error-demonlist-duplicatevideo = This video is already used by record #{ $record-id }
error-demonlist-nonationset = Attempt to set subdivision without nation
error-demonlist-conflictingclaims = The players '{ $player-1 }' and '{ $player-2 }' have verified claims by different pointercrate users
error-demonlist-invalidrequirement = Record requirement needs to be greater than -1 and smaller than 101
error-demonlist-invalidposition = Demon position needs to be greater than or equal to 1 and smaller than or equal to { $maximal }
error-demonlist-invalidprogress = Record progress must lie between { $requirement } and 100%!
error-demonlist-submissionexists = This record is already { $record-status } (existing record: { $record-id })
error-demonlist-playerbanned = The given player is banned and thus cannot have non-rejected records on the list!
error-demonlist-submitlegacy = You cannot submit records for legacy demons
error-demonlist-non100extended = Only 100% records can be submitted for the extended section of the list
error-demonlist-unsupportedvideohost = The given video host is not supported. Supported are 'youtube', 'vimeo', 'everyplay', 'twitch' and 'bilibili'
error-demonlist-demonnamenotunique = There are multiple demons with the given name
error-demonlist-noteempty = Notes mustn't be empty!
error-demonlist-alreadyclaimed = This player already has a verified claim associated with them
error-demonlist-rawrequired = Raw footage much be provided to submit this record
error-demonlist-malformedrawurl = Raw footage needs to be a valid URL
error-demonlist-invalidlevelid = Level ID needs to be positive

error-demonlist-ratelimit-record-submit = You're submitting too many records too fast!
error-demonlist-ratelimit-record-submit-global = Too many records are being submitted right now!
error-demonlist-ratelimit-new-submitters = DDoS protection ratelimit
error-demonlist-ratelimit-add-demon = Please don't spam the button, rSteel