error-demonlist-malformedvideourl = Неправильная ссылка на видео
error-demonlist-bannedfromsubmissions = Вы забанены в демонлисте!
error-demonlist-claimunverified = Ваш запрос на присвоение профиля не подтвержден
error-demonlist-vpsdetected = Была обнаружена попытка IP-геолокации через VPS
error-demonlist-nothirdpartysubmissions = Этот игрок указал, что только он сам может отправлять свои рекорды
error-demonlist-submitternotfound = Отправитель с id { $id } не был найден
error-demonlist-notenotfound = Записка с id { $note-id } не была найдена на рекорде с id { $record-id }
error-demonlist-creatornotfound = Игрок с id { $player-id } не является креатором демона с id { demon-id }
error-demonlist-nationalitynotfound = Страна с iso-кодом { $iso-code } не была найдена
error-demonlist-subdivisionnotfound = Регион с кодом { $subdivision-code } не был найден в стране { $nation-code }
error-demonlist-playernotfound = Игрок с id { $player-id } не был найден
error-demonlist-playernotfoundname = Игрок с именем { $player-name } не был найден
error-demonlist-demonnotfound = Демон с id { $demon-id } не был найден
error-demonlist-demonnotfoundname = Демон с именем { $demon-name } не был найден
error-demonlist-demonnotfoundposition = Демон на позиции { $demon-position } не был найден
error-demonlist-recordnotfound = Рекорд с id { $record-id } не был найден
error-demonlist-claimnotfound = Запрос пользователем { $member-id } на присвоение профиля { $player-id } не был найден
error-demonlist-creatorexists = Этот игрок уже указан как креатор на этом демоне
error-demonlist-duplicatevideo = Это видео уже используется рекордом #{ $record-id }
error-demonlist-nonationset = Попытка установить регион без страны
error-demonlist-conflictingclaims = Игроки '{ $player-1 }' и '{ $player-2 }' имеют подтвержденные присвоения разными пользователями pointercrate
error-demonlist-invalidrequirement = Требование к рекорду должно быть больше -1 и меньше 101
error-demonlist-invalidposition = Позиция демона должна быть между 1 и { $maximal }
error-demonlist-invalidprogress = Прогресс на рекорде должен находиться между { $requirement } и 100%!
error-demonlist-submissionexists = Такой рекорд со статусом '{ $record-status }' уже существует (имеющийся рекорд: { $record-id })
error-demonlist-playerbanned = Данный игрок забанен и потому не может иметь неотклоненные рекорды!
error-demonlist-submitlegacy = Вы не можете отправлять рекорды для legacy-демонов
error-demonlist-non100extended = Для extended-части листа можно отправлять только прохождения
error-demonlist-unsupportedvideohost = Данный видеохостинг не поддерживается. Поддерживаются следующие: 'youtube', 'vimeo', 'everyplay', 'twitch' и 'bilibili'
error-demonlist-demonnamenotunique = С данным названием существует сразу несколько демонов
error-demonlist-noteempty = Записки не должны быть пустыми!
error-demonlist-alreadyclaimed = Этот игрок уже имеет связанное с собой присвоение профиля
error-demonlist-rawrequired = Для отправки рекорда необходимо предоставить необработанную запись
error-demonlist-malformedrawurl = Необработанная запись должна быть в виде правильно оформленной ссылки
error-demonlist-invalidlevelid = ID уровня должен быть положительным

error-demonlist-ratelimit-record-submit = Вы отправляете слишком много рекордов слишком часто!
error-demonlist-ratelimit-record-submit-global = Слишком много рекордов отправляется на данный момент!
error-demonlist-ratelimit-new-submitters = Ограничение запросов для DDoS-защиты
error-demonlist-ratelimit-add-demon = Поаккуратнее с кнопкой бро